version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  line-provider:
    build:
      context: ./line_provider
    environment:
      DB_URL: ${DB_URL}
      QUEUE_URL: ${QUEUE_URL}
      LINE_PROVIDER_URL: ${LINE_PROVIDER_URL}
    depends_on:
      - rabbitmq
      - postgres
    networks:
      - app-network
    ports:
      - "8080:8080"

  bet-maker:
    build:
      context: ./bet_maker
    environment:
      DB_URL: ${DB_URL}
      QUEUE_URL: ${QUEUE_URL}
      LINE_PROVIDER_URL: ${LINE_PROVIDER_URL}
    depends_on:
      - rabbitmq
      - postgres
    networks:
      - app-network
    ports:
      - "8000:8000"

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge